version: '3'
services:
  healthy-spring-boot-logging:
    build:
      context: .
      dockerfile: docker/healthy-spring-boot-logging/Dockerfile
    ports:
      - 8080:8080
  unhealthy-spring-boot-logging:
    build:
      context: .
      dockerfile: docker/unhealthy-spring-boot-logging/Dockerfile
    ports:
      - 8079:8080
  prometheus:
    image: prom/prometheus:v2.12.0
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:6.3.5
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana:/etc/grafana
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      - discovery.type=single-node
