version: '3'
services:
  healthy-spring-boot-logging:
    build:
      context: .
      dockerfile: docker/healthy-spring-boot-logging/Dockerfile
    ports:
      - 8080:8080
  unhealthy-spring-boot-logging:
    build:
      context: .
      dockerfile: docker/unhealthy-spring-boot-logging/Dockerfile
    ports:
      - 8079:8080
  prometheus:
    build:
      context: .
      dockerfile: docker/prometheus/Dockerfile
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:6.3.5
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana:/etc/grafana
